/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv_amain;

import java.awt.Color;
import java.awt.Image;//nav icon
import javax.swing.Icon;//nav icon
import javax.swing.ImageIcon;//nav icon

import javax.swing.*;//minimize
import java.awt.geom.RoundRectangle2D;
import java.sql.*;//mysql
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PREDATOR HELIOS 300
 */
public class A_ForgotForm extends javax.swing.JFrame {

    //mysql
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    //Draggable Frame
    int positionX = 0, positionY = 0;

    public A_ForgotForm() {
        initComponents();
        //logo change
        Image imgLogo = new ImageIcon(this.getClass().getResource("/inv_images/LCBC_logo_pr.png")).getImage();
        this.setIconImage(imgLogo);
        //mysql
        conn = SQLConnection.getConnection();

        //focus on panel
        //ForgotMainPanel.setFocusable(true);
        //Red Icon
        Icon red = exitBtn.getIcon();
        ImageIcon iconR = (ImageIcon) red;
        Image imageR = iconR.getImage().getScaledInstance(exitBtn.getWidth(), exitBtn.getHeight(), Image.SCALE_SMOOTH);
        exitBtn.setIcon(new ImageIcon(imageR));
        //Yellow Icon
        Icon yellow = minimizeBtn.getIcon();
        ImageIcon iconY = (ImageIcon) yellow;
        Image imageY = iconY.getImage().getScaledInstance(minimizeBtn.getWidth(), minimizeBtn.getHeight(), Image.SCALE_SMOOTH);
        minimizeBtn.setIcon(new ImageIcon(imageY));

        //Rounder Corner
        // x,y,jframe width,jframe height,arc width,arc height
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotMainPanel = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        LoginBtn = new com.k33ptoo.components.KButton();
        ForgotLabel2 = new javax.swing.JLabel();
        ForgotLabel3 = new javax.swing.JLabel();
        ForgotLabel4 = new javax.swing.JLabel();
        txtAns = new javax.swing.JTextField();
        ForgotLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        recBtn = new com.k33ptoo.components.KButton();
        txtUname = new javax.swing.JTextField();
        txtQues = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ForgotMainPanel.setBackground(new java.awt.Color(245, 215, 189));
        ForgotMainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(80, 42, 178)));
        ForgotMainPanel.setMaximumSize(new java.awt.Dimension(600, 500));
        ForgotMainPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        NavBar.setBackground(new java.awt.Color(80, 42, 178));
        NavBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                NavBarMouseDragged(evt);
            }
        });
        NavBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavBarMousePressed(evt);
            }
        });

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inv_images/red.png"))); // NOI18N
        exitBtn.setToolTipText("Close");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inv_images/yellow.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginBtn.setText("GO BACK");
        LoginBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        LoginBtn.setkBorderRadius(30);
        LoginBtn.setkEndColor(new java.awt.Color(80, 42, 178));
        LoginBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        LoginBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        LoginBtn.setkHoverForeGround(new java.awt.Color(80, 42, 178));
        LoginBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        LoginBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        LoginBtn.setkStartColor(new java.awt.Color(80, 42, 178));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        ForgotLabel2.setFont(new java.awt.Font("Retro Computer", 0, 13)); // NOI18N
        ForgotLabel2.setForeground(new java.awt.Color(0, 0, 0));
        ForgotLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ForgotLabel2.setText("USERNAME");

        ForgotLabel3.setFont(new java.awt.Font("Retro Computer", 0, 13)); // NOI18N
        ForgotLabel3.setForeground(new java.awt.Color(0, 0, 0));
        ForgotLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ForgotLabel3.setText("security question");

        ForgotLabel4.setFont(new java.awt.Font("Retro Computer", 0, 13)); // NOI18N
        ForgotLabel4.setForeground(new java.awt.Color(0, 0, 0));
        ForgotLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ForgotLabel4.setText("answer");

        txtAns.setBackground(new java.awt.Color(245, 215, 189));
        txtAns.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtAns.setBorder(null);
        txtAns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnsKeyPressed(evt);
            }
        });

        ForgotLabel5.setFont(new java.awt.Font("Retro Computer", 0, 13)); // NOI18N
        ForgotLabel5.setForeground(new java.awt.Color(0, 0, 0));
        ForgotLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ForgotLabel5.setText("Your password");

        txtPass.setBackground(new java.awt.Color(245, 215, 189));
        txtPass.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtPass.setBorder(null);

        recBtn.setText("recover");
        recBtn.setFont(new java.awt.Font("Retro Computer", 1, 18)); // NOI18N
        recBtn.setkBorderRadius(30);
        recBtn.setkEndColor(new java.awt.Color(80, 42, 178));
        recBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        recBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        recBtn.setkHoverForeGround(new java.awt.Color(80, 42, 178));
        recBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        recBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        recBtn.setkStartColor(new java.awt.Color(80, 42, 178));
        recBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recBtnActionPerformed(evt);
            }
        });

        txtUname.setBackground(new java.awt.Color(245, 215, 189));
        txtUname.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtUname.setForeground(new java.awt.Color(0, 0, 0));
        txtUname.setBorder(null);
        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnameKeyReleased(evt);
            }
        });

        txtQues.setFont(new java.awt.Font("Retro Computer", 0, 11)); // NOI18N
        txtQues.setForeground(new java.awt.Color(0, 0, 0));
        txtQues.setText("(question will appear here)");

        jPanel1.setBackground(new java.awt.Color(80, 42, 178));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(80, 42, 178));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(80, 42, 178));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ForgotMainPanelLayout = new javax.swing.GroupLayout(ForgotMainPanel);
        ForgotMainPanel.setLayout(ForgotMainPanelLayout);
        ForgotMainPanelLayout.setHorizontalGroup(
            ForgotMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForgotMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ForgotMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ForgotMainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ForgotMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUname)
                        .addComponent(txtAns)
                        .addComponent(txtPass)
                        .addComponent(ForgotLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQues, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(ForgotLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ForgotLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ForgotLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(172, 172, 172))
        );
        ForgotMainPanelLayout.setVerticalGroup(
            ForgotMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotMainPanelLayout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ForgotLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForgotLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtQues, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ForgotLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtAns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ForgotLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(recBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ForgotMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ForgotMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void recover() {
        String ans = txtAns.getText();
        String usr = txtUname.getText();
        if (usr.equals("")) {

            JOptionPane.showMessageDialog(null, "Please fill the username to show security question");
            txtPass.setText("");
        } else if (ans.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill the answer to retreive password");
            txtPass.setText("");
        } else {
            try {
                String sq = "SELECT * FROM `user` WHERE `uname` = '" + usr + "' AND `ans`='" + ans + "'";
                ps = conn.prepareStatement(sq);
                rs = ps.executeQuery();
                if (rs.next()) {
                    String pwanswer = rs.getString(3/*3 means pass in our user table structure*/);
                    //JOptionPane.showMessageDialog(null, "Your password is: "+pwanswer);// Optional Popup to show pass
                    txtPass.setText(pwanswer);

                } else {
                    JOptionPane.showMessageDialog(null, "Answer is not match with database");
                    txtAns.setText("");
                    txtPass.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        //minimize
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void NavBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBarMouseDragged
        //Draggable Frame set JFrame Location
        setLocation(evt.getXOnScreen() - positionX, evt.getYOnScreen() - positionY);
    }//GEN-LAST:event_NavBarMouseDragged

    private void NavBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBarMousePressed
        //Draggable Frame Get Jfram Coord value
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_NavBarMousePressed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        A_LoginForm L = new A_LoginForm();
        L.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LoginBtnActionPerformed

    private void recBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recBtnActionPerformed
        recover();
    }//GEN-LAST:event_recBtnActionPerformed

    private void txtUnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyReleased
        try {
            String sql = "SELECT * FROM `user` WHERE `uname` =?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtUname.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                txtQues.setText(rs.getString("ques"));
                txtAns.setText("");
                txtPass.setText("");

            } else {

                txtQues.setText("(question will appear here)");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtUnameKeyReleased

    private void txtAnsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            recover();
        }
    }//GEN-LAST:event_txtAnsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_ForgotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotLabel2;
    private javax.swing.JLabel ForgotLabel3;
    private javax.swing.JLabel ForgotLabel4;
    private javax.swing.JLabel ForgotLabel5;
    private javax.swing.JPanel ForgotMainPanel;
    private com.k33ptoo.components.KButton LoginBtn;
    private javax.swing.JPanel NavBar;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel minimizeBtn;
    private com.k33ptoo.components.KButton recBtn;
    private javax.swing.JTextField txtAns;
    private javax.swing.JTextField txtPass;
    private javax.swing.JLabel txtQues;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
