/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv_amain;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR HELIOS 300
 */
public class B_CustomerPanel extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet st = null;
    PreparedStatement ps = null;

    public B_CustomerPanel() {
        initComponents();
        //mysql
        conn = SQLConnection.getConnection();
        customerTB_load();
        disablePaste(txtCustomerID);
        disablePaste(txtContactNum);
        disablePaste(txtReceivables);
    }

    //disable copy paste
    public void disableCopy(JComponent component) {
        component.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
    }

    public void disablePaste(JComponent component) {
        component.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");
    }

    public void disableCopyPaste(JComponent component) {
        disableCopy(component);
        disablePaste(component);
    }

    public void customerTB_load() {
        try {
            DefaultTableModel dt = (DefaultTableModel) cust_table.getModel();
            dt.setRowCount(0);
            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM customer");
            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));

                dt.addRow(v);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeePanel = new javax.swing.JPanel();
        CustomerPanelLbl = new javax.swing.JLabel();
        CustomerIDLbl = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        Line1 = new javax.swing.JPanel();
        CustSearchBtn = new com.k33ptoo.components.KButton();
        CustnameLbl = new javax.swing.JLabel();
        txtCustname = new javax.swing.JTextField();
        Line2 = new javax.swing.JPanel();
        EmailLbl = new javax.swing.JLabel();
        txtCustEmail = new javax.swing.JTextField();
        Line3 = new javax.swing.JPanel();
        ContactLbl = new javax.swing.JLabel();
        txtContactNum = new javax.swing.JTextField();
        Line4 = new javax.swing.JPanel();
        ReceivablesLbl = new javax.swing.JLabel();
        txtReceivables = new javax.swing.JTextField();
        Line5 = new javax.swing.JPanel();
        CustSaveBtn = new com.k33ptoo.components.KButton();
        CustDelBtn = new com.k33ptoo.components.KButton();
        CustUpdateBtn = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cust_table = new rojeru_san.complementos.TableMetro();
        CustClearField = new com.k33ptoo.components.KButton();

        setMaximumSize(new java.awt.Dimension(890, 650));
        setPreferredSize(new java.awt.Dimension(890, 650));

        EmployeePanel.setBackground(new java.awt.Color(245, 215, 189));
        EmployeePanel.setForeground(new java.awt.Color(245, 215, 189));
        EmployeePanel.setMaximumSize(new java.awt.Dimension(890, 650));
        EmployeePanel.setPreferredSize(new java.awt.Dimension(890, 650));

        CustomerPanelLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustomerPanelLbl.setFont(new java.awt.Font("Retro Computer", 1, 18)); // NOI18N
        CustomerPanelLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustomerPanelLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerPanelLbl.setText("customers list");
        CustomerPanelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CustomerIDLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustomerIDLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        CustomerIDLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustomerIDLbl.setText("Search customer ID");

        txtCustomerID.setBackground(new java.awt.Color(245, 215, 189));
        txtCustomerID.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtCustomerID.setForeground(new java.awt.Color(0, 0, 0));
        txtCustomerID.setBorder(null);
        txtCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerIDKeyTyped(evt);
            }
        });

        Line1.setBackground(new java.awt.Color(175, 157, 206));
        Line1.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line1Layout = new javax.swing.GroupLayout(Line1);
        Line1.setLayout(Line1Layout);
        Line1Layout.setHorizontalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line1Layout.setVerticalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        CustSearchBtn.setText("search");
        CustSearchBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        CustSearchBtn.setkBorderRadius(30);
        CustSearchBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        CustSearchBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        CustSearchBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        CustSearchBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        CustSearchBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        CustSearchBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        CustSearchBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        CustSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustSearchBtnActionPerformed(evt);
            }
        });

        CustnameLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustnameLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        CustnameLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustnameLbl.setText("customer name");

        txtCustname.setBackground(new java.awt.Color(245, 215, 189));
        txtCustname.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtCustname.setForeground(new java.awt.Color(0, 0, 0));
        txtCustname.setBorder(null);
        txtCustname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustnameKeyTyped(evt);
            }
        });

        Line2.setBackground(new java.awt.Color(175, 157, 206));
        Line2.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line2Layout = new javax.swing.GroupLayout(Line2);
        Line2.setLayout(Line2Layout);
        Line2Layout.setHorizontalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line2Layout.setVerticalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        EmailLbl.setBackground(new java.awt.Color(0, 0, 0));
        EmailLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(0, 0, 0));
        EmailLbl.setText("email");

        txtCustEmail.setBackground(new java.awt.Color(245, 215, 189));
        txtCustEmail.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtCustEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtCustEmail.setBorder(null);
        txtCustEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustEmailKeyReleased(evt);
            }
        });

        Line3.setBackground(new java.awt.Color(175, 157, 206));
        Line3.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line3Layout = new javax.swing.GroupLayout(Line3);
        Line3.setLayout(Line3Layout);
        Line3Layout.setHorizontalGroup(
            Line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line3Layout.setVerticalGroup(
            Line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ContactLbl.setBackground(new java.awt.Color(0, 0, 0));
        ContactLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        ContactLbl.setForeground(new java.awt.Color(0, 0, 0));
        ContactLbl.setText("Contact number");

        txtContactNum.setBackground(new java.awt.Color(245, 215, 189));
        txtContactNum.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtContactNum.setForeground(new java.awt.Color(0, 0, 0));
        txtContactNum.setBorder(null);
        txtContactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNumKeyTyped(evt);
            }
        });

        Line4.setBackground(new java.awt.Color(175, 157, 206));
        Line4.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line4Layout = new javax.swing.GroupLayout(Line4);
        Line4.setLayout(Line4Layout);
        Line4Layout.setHorizontalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line4Layout.setVerticalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ReceivablesLbl.setBackground(new java.awt.Color(0, 0, 0));
        ReceivablesLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        ReceivablesLbl.setForeground(new java.awt.Color(0, 0, 0));
        ReceivablesLbl.setText("receivables");

        txtReceivables.setBackground(new java.awt.Color(245, 215, 189));
        txtReceivables.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        txtReceivables.setForeground(new java.awt.Color(0, 0, 0));
        txtReceivables.setBorder(null);
        txtReceivables.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReceivablesKeyTyped(evt);
            }
        });

        Line5.setBackground(new java.awt.Color(175, 157, 206));
        Line5.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line5Layout = new javax.swing.GroupLayout(Line5);
        Line5.setLayout(Line5Layout);
        Line5Layout.setHorizontalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line5Layout.setVerticalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        CustSaveBtn.setText("save");
        CustSaveBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        CustSaveBtn.setkBorderRadius(30);
        CustSaveBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        CustSaveBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        CustSaveBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        CustSaveBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        CustSaveBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        CustSaveBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        CustSaveBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        CustSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustSaveBtnActionPerformed(evt);
            }
        });

        CustDelBtn.setText("delete");
        CustDelBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        CustDelBtn.setkBorderRadius(30);
        CustDelBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        CustDelBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        CustDelBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        CustDelBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        CustDelBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        CustDelBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        CustDelBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        CustDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustDelBtnActionPerformed(evt);
            }
        });

        CustUpdateBtn.setText("update");
        CustUpdateBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        CustUpdateBtn.setkBorderRadius(30);
        CustUpdateBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        CustUpdateBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        CustUpdateBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        CustUpdateBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        CustUpdateBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        CustUpdateBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        CustUpdateBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        CustUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustUpdateBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(245, 215, 189));
        jScrollPane1.setForeground(new java.awt.Color(245, 215, 189));

        cust_table.setBackground(new java.awt.Color(245, 215, 189));
        cust_table.setForeground(new java.awt.Color(245, 215, 189));
        cust_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CustID", "CustName", "Email", "Contact", "Receivables"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cust_table.setColorBackgoundHead(new java.awt.Color(142, 126, 167));
        cust_table.setColorBordeFilas(new java.awt.Color(175, 157, 206));
        cust_table.setColorBordeHead(new java.awt.Color(175, 157, 206));
        cust_table.setColorFilasBackgound1(new java.awt.Color(245, 215, 189));
        cust_table.setColorFilasBackgound2(new java.awt.Color(245, 215, 189));
        cust_table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        cust_table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        cust_table.setColorForegroundHead(new java.awt.Color(245, 215, 189));
        cust_table.setColorSelBackgound(new java.awt.Color(255, 255, 255));
        cust_table.setColorSelForeground(new java.awt.Color(0, 0, 0));
        cust_table.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cust_table.setFuenteFilas(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cust_table.setFuenteFilasSelect(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cust_table.setFuenteHead(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        cust_table.setGridColor(new java.awt.Color(175, 157, 206));
        cust_table.setRowHeight(25);
        cust_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        cust_table.setSelectionForeground(new java.awt.Color(245, 215, 189));
        cust_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cust_table);

        CustClearField.setText("Clear fields");
        CustClearField.setToolTipText("");
        CustClearField.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        CustClearField.setkBorderRadius(30);
        CustClearField.setkEndColor(new java.awt.Color(175, 157, 206));
        CustClearField.setkForeGround(new java.awt.Color(245, 215, 189));
        CustClearField.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        CustClearField.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        CustClearField.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        CustClearField.setkPressedColor(new java.awt.Color(242, 179, 65));
        CustClearField.setkStartColor(new java.awt.Color(175, 157, 206));
        CustClearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustClearFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerIDLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerPanelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePanelLayout.createSequentialGroup()
                                .addComponent(CustSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustnameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustname, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addComponent(CustSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustClearField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CustDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtReceivables, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReceivablesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerPanelLbl)
                .addGap(18, 18, 18)
                .addComponent(CustomerIDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CustSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(CustClearField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(EmailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(CustnameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ContactLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ReceivablesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReceivables, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CustSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustSaveBtnActionPerformed

        String fname = txtCustname.getText();
        String email = txtCustEmail.getText();
        String cpn = txtContactNum.getText();
        String receivables = txtReceivables.getText();
        int savebtn = JOptionPane.showConfirmDialog(null, "Are you sure you want to save this record?", "Save Record", JOptionPane.YES_NO_OPTION);
        if (savebtn == 0) {
            try {
                if (fname.isEmpty() || email.isEmpty() || cpn.isEmpty() || receivables.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Don't leave fields empty");
                } else if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$")) {
                    //^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$
                    //^.+@.+\\..+$
                    JOptionPane.showMessageDialog(null, "invalid email format");
                } else {
                    String sql = "INSERT INTO `customer`(`cust_NAME`, `cust_EMAIL`, `cust_CPNUM`, `cust_RCV`) VALUES (?,?,?,?)";
                    ps = conn.prepareStatement(sql);

                    ps.setString(1, txtCustname.getText());
                    ps.setString(2, txtCustEmail.getText());
                    ps.setString(3, txtContactNum.getText()); //validate only number and must start at 09 regex: ^09\d{9}$
                    ps.setString(4, txtReceivables.getText()); //validate only number regex: ^\d{1,8}$

                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Data saved successfully");
                    customerTB_load();
                    txtCustomerID.setText("");
                    txtCustname.setText("");
                    txtCustEmail.setText("");
                    txtContactNum.setText("");
                    txtReceivables.setText("");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_CustSaveBtnActionPerformed

    private void CustSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustSearchBtnActionPerformed

        String search = txtCustomerID.getText();
        try {
            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM customer WHERE cust_ID ='" + search + "' ");
            if (rs.next()) {
                txtCustname.setText(rs.getString("cust_NAME"));
                txtCustEmail.setText(rs.getString("cust_EMAIL"));
                txtContactNum.setText(rs.getString("cust_CPNUM"));
                txtReceivables.setText(rs.getString("cust_RCV"));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CustSearchBtnActionPerformed

    private void CustUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustUpdateBtnActionPerformed
        String id = txtCustomerID.getText();
        String fname = txtCustname.getText();
        String email = txtCustEmail.getText();
        String cpn = txtContactNum.getText();
        String receivables = txtReceivables.getText();
        try {
            if (id.isEmpty() || fname.isEmpty() || email.isEmpty() || cpn.isEmpty() || receivables.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Don't leave fields empty");
            } else if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$")) {
                //^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$
                //^.+@.+\\..+$
                JOptionPane.showMessageDialog(null, "invalid email format");
            } else {
                Statement s = SQLConnection.getConnection().createStatement();
                s.executeUpdate("UPDATE customer SET cust_NAME='" + fname + "' ,cust_EMAIL='" + email + "' ,cust_CPNUM='" + cpn + "' ,cust_RCV='" + receivables + "' WHERE cust_ID='" + id + "'");

                JOptionPane.showMessageDialog(null, "Data updated successfully");
                customerTB_load();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CustUpdateBtnActionPerformed

    private void CustDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustDelBtnActionPerformed
        String id = txtCustomerID.getText();
        try {
            Statement s = SQLConnection.getConnection().createStatement();
            s.executeUpdate("DELETE FROM customer WHERE cust_ID='" + id + "'");

            JOptionPane.showMessageDialog(null, "Data deleted successfully");
            customerTB_load();
            txtCustomerID.setText("");
            txtCustname.setText("");
            txtCustEmail.setText("");
            txtContactNum.setText("");
            txtReceivables.setText("");

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_CustDelBtnActionPerformed

    private void cust_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_tableMouseClicked
        //mouse click & data to textfield
        int r = cust_table.getSelectedRow();

        String id = cust_table.getValueAt(r, 0).toString();
        String name = cust_table.getValueAt(r, 1).toString();
        String email = cust_table.getValueAt(r, 2).toString();
        String contact = cust_table.getValueAt(r, 3).toString();
        String rcv = cust_table.getValueAt(r, 4).toString();

        txtCustomerID.setText(id);
        txtCustname.setText(name);
        txtCustEmail.setText(email);
        txtContactNum.setText(contact);
        txtReceivables.setText(rcv);
    }//GEN-LAST:event_cust_tableMouseClicked

    private void CustClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustClearFieldActionPerformed
        txtCustomerID.setText("");
        txtCustname.setText("");
        txtCustEmail.setText("");
        txtContactNum.setText("");
        txtReceivables.setText("");
    }//GEN-LAST:event_CustClearFieldActionPerformed

    private void txtCustomerIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIDKeyTyped
        char c = evt.getKeyChar();
        if (txtCustomerID.getText().length() >= 8) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerIDKeyTyped

    private void txtCustnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustnameKeyTyped
        char c = evt.getKeyChar();
        if (txtCustname.getText().length() >= 55) {
            evt.consume();
        } else if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCustnameKeyTyped

    private void txtContactNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNumKeyTyped
        char c = evt.getKeyChar();
        if (txtContactNum.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContactNumKeyTyped

    private void txtReceivablesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReceivablesKeyTyped
        char c = evt.getKeyChar();
        if (txtReceivables.getText().length() >= 8) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtReceivablesKeyTyped

    private void txtCustnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustnameKeyReleased
        int position = txtCustname.getCaretPosition();
        txtCustname.setText(txtCustname.getText().toUpperCase());
        txtCustname.setCaretPosition(position);
    }//GEN-LAST:event_txtCustnameKeyReleased

    private void txtCustEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustEmailKeyReleased
        int position = txtCustEmail.getCaretPosition();
        txtCustEmail.setText(txtCustEmail.getText().toUpperCase());
        txtCustEmail.setCaretPosition(position);
    }//GEN-LAST:event_txtCustEmailKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactLbl;
    private com.k33ptoo.components.KButton CustClearField;
    private com.k33ptoo.components.KButton CustDelBtn;
    private com.k33ptoo.components.KButton CustSaveBtn;
    private com.k33ptoo.components.KButton CustSearchBtn;
    private com.k33ptoo.components.KButton CustUpdateBtn;
    private javax.swing.JLabel CustnameLbl;
    private javax.swing.JLabel CustomerIDLbl;
    private javax.swing.JLabel CustomerPanelLbl;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JPanel Line1;
    private javax.swing.JPanel Line2;
    private javax.swing.JPanel Line3;
    private javax.swing.JPanel Line4;
    private javax.swing.JPanel Line5;
    private javax.swing.JLabel ReceivablesLbl;
    private rojeru_san.complementos.TableMetro cust_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtCustEmail;
    private javax.swing.JTextField txtCustname;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtReceivables;
    // End of variables declaration//GEN-END:variables
}
