/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv_amain;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR HELIOS 300
 */
public class B_EmployeePanel extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet st = null;
    PreparedStatement ps = null;

    public B_EmployeePanel() {
        initComponents();
        //mysql
        conn = SQLConnection.getConnection();
        customerTB_load();

    }

    public void customerTB_load() {
        try {
            DefaultTableModel dt = (DefaultTableModel) emp_table.getModel();
            dt.setRowCount(0);
            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM employee");
            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));

                dt.addRow(v);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeePanel = new javax.swing.JPanel();
        CustomerPanelLbl = new javax.swing.JLabel();
        CustomerIDLbl = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        Line1 = new javax.swing.JPanel();
        EmpSearchBtn = new com.k33ptoo.components.KButton();
        CustnameLbl = new javax.swing.JLabel();
        txtEmpFName = new javax.swing.JTextField();
        Line2 = new javax.swing.JPanel();
        EmailLbl = new javax.swing.JLabel();
        txtEmpLName = new javax.swing.JTextField();
        Line3 = new javax.swing.JPanel();
        ContactLbl = new javax.swing.JLabel();
        txtEmpContact = new javax.swing.JTextField();
        Line4 = new javax.swing.JPanel();
        ReceivablesLbl = new javax.swing.JLabel();
        txtEmpSalary = new javax.swing.JTextField();
        Line5 = new javax.swing.JPanel();
        EmpSaveBtn = new com.k33ptoo.components.KButton();
        EmpDelBtn = new com.k33ptoo.components.KButton();
        EmpUpdateBtn = new com.k33ptoo.components.KButton();
        txtEmpPositionCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_table = new rojeru_san.complementos.TableMetro();
        EmpClearFields = new com.k33ptoo.components.KButton();
        EmailLbl1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 650));
        setPreferredSize(new java.awt.Dimension(890, 650));

        EmployeePanel.setBackground(new java.awt.Color(245, 215, 189));
        EmployeePanel.setForeground(new java.awt.Color(245, 215, 189));
        EmployeePanel.setMaximumSize(new java.awt.Dimension(890, 650));
        EmployeePanel.setPreferredSize(new java.awt.Dimension(890, 650));

        CustomerPanelLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustomerPanelLbl.setFont(new java.awt.Font("Retro Computer", 1, 18)); // NOI18N
        CustomerPanelLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustomerPanelLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerPanelLbl.setText("Employee list");
        CustomerPanelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CustomerIDLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustomerIDLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        CustomerIDLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustomerIDLbl.setText("Search employee ID");

        txtEmployeeID.setBackground(new java.awt.Color(245, 215, 189));
        txtEmployeeID.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 0));
        txtEmployeeID.setBorder(null);
        txtEmployeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmployeeIDKeyTyped(evt);
            }
        });

        Line1.setBackground(new java.awt.Color(175, 157, 206));
        Line1.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line1Layout = new javax.swing.GroupLayout(Line1);
        Line1.setLayout(Line1Layout);
        Line1Layout.setHorizontalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line1Layout.setVerticalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        EmpSearchBtn.setText("search");
        EmpSearchBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        EmpSearchBtn.setkBorderRadius(30);
        EmpSearchBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        EmpSearchBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        EmpSearchBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        EmpSearchBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        EmpSearchBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        EmpSearchBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        EmpSearchBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        EmpSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSearchBtnActionPerformed(evt);
            }
        });

        CustnameLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustnameLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        CustnameLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustnameLbl.setText("first name");

        txtEmpFName.setBackground(new java.awt.Color(245, 215, 189));
        txtEmpFName.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtEmpFName.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpFName.setBorder(null);
        txtEmpFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpFNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpFNameKeyTyped(evt);
            }
        });

        Line2.setBackground(new java.awt.Color(175, 157, 206));
        Line2.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line2Layout = new javax.swing.GroupLayout(Line2);
        Line2.setLayout(Line2Layout);
        Line2Layout.setHorizontalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line2Layout.setVerticalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        EmailLbl.setBackground(new java.awt.Color(0, 0, 0));
        EmailLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(0, 0, 0));
        EmailLbl.setText("last name");

        txtEmpLName.setBackground(new java.awt.Color(245, 215, 189));
        txtEmpLName.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtEmpLName.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpLName.setBorder(null);
        txtEmpLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpLNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpLNameKeyTyped(evt);
            }
        });

        Line3.setBackground(new java.awt.Color(175, 157, 206));
        Line3.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line3Layout = new javax.swing.GroupLayout(Line3);
        Line3.setLayout(Line3Layout);
        Line3Layout.setHorizontalGroup(
            Line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line3Layout.setVerticalGroup(
            Line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ContactLbl.setBackground(new java.awt.Color(0, 0, 0));
        ContactLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        ContactLbl.setForeground(new java.awt.Color(0, 0, 0));
        ContactLbl.setText("Contact number");

        txtEmpContact.setBackground(new java.awt.Color(245, 215, 189));
        txtEmpContact.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtEmpContact.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpContact.setBorder(null);
        txtEmpContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpContactKeyTyped(evt);
            }
        });

        Line4.setBackground(new java.awt.Color(175, 157, 206));
        Line4.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line4Layout = new javax.swing.GroupLayout(Line4);
        Line4.setLayout(Line4Layout);
        Line4Layout.setHorizontalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line4Layout.setVerticalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ReceivablesLbl.setBackground(new java.awt.Color(0, 0, 0));
        ReceivablesLbl.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        ReceivablesLbl.setForeground(new java.awt.Color(0, 0, 0));
        ReceivablesLbl.setText("salary");

        txtEmpSalary.setBackground(new java.awt.Color(245, 215, 189));
        txtEmpSalary.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        txtEmpSalary.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpSalary.setBorder(null);
        txtEmpSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpSalaryKeyTyped(evt);
            }
        });

        Line5.setBackground(new java.awt.Color(175, 157, 206));
        Line5.setPreferredSize(new java.awt.Dimension(258, 3));

        javax.swing.GroupLayout Line5Layout = new javax.swing.GroupLayout(Line5);
        Line5.setLayout(Line5Layout);
        Line5Layout.setHorizontalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line5Layout.setVerticalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        EmpSaveBtn.setText("save");
        EmpSaveBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        EmpSaveBtn.setkBorderRadius(30);
        EmpSaveBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        EmpSaveBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        EmpSaveBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        EmpSaveBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        EmpSaveBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        EmpSaveBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        EmpSaveBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        EmpSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSaveBtnActionPerformed(evt);
            }
        });

        EmpDelBtn.setText("delete");
        EmpDelBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        EmpDelBtn.setkBorderRadius(30);
        EmpDelBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        EmpDelBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        EmpDelBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        EmpDelBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        EmpDelBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        EmpDelBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        EmpDelBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        EmpDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpDelBtnActionPerformed(evt);
            }
        });

        EmpUpdateBtn.setText("update");
        EmpUpdateBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        EmpUpdateBtn.setkBorderRadius(30);
        EmpUpdateBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        EmpUpdateBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        EmpUpdateBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        EmpUpdateBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        EmpUpdateBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        EmpUpdateBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        EmpUpdateBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        EmpUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpUpdateBtnActionPerformed(evt);
            }
        });

        txtEmpPositionCB.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpPositionCB.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        txtEmpPositionCB.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpPositionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Co-Owner", "Supply Chain Manager", "Inventory Clerk" }));
        txtEmpPositionCB.setSelectedItem(null);
        txtEmpPositionCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(245, 215, 189));
        jScrollPane1.setForeground(new java.awt.Color(245, 215, 189));

        emp_table.setBackground(new java.awt.Color(245, 215, 189));
        emp_table.setForeground(new java.awt.Color(245, 215, 189));
        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EmpID", "FName", "LName", "POS", "Contact", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        emp_table.setColorBackgoundHead(new java.awt.Color(142, 126, 167));
        emp_table.setColorBordeFilas(new java.awt.Color(175, 157, 206));
        emp_table.setColorBordeHead(new java.awt.Color(175, 157, 206));
        emp_table.setColorFilasBackgound1(new java.awt.Color(245, 215, 189));
        emp_table.setColorFilasBackgound2(new java.awt.Color(245, 215, 189));
        emp_table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        emp_table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        emp_table.setColorForegroundHead(new java.awt.Color(245, 215, 189));
        emp_table.setColorSelBackgound(new java.awt.Color(255, 255, 255));
        emp_table.setColorSelForeground(new java.awt.Color(0, 0, 0));
        emp_table.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        emp_table.setFuenteFilas(new java.awt.Font("Arial", 0, 10)); // NOI18N
        emp_table.setFuenteFilasSelect(new java.awt.Font("Arial", 0, 10)); // NOI18N
        emp_table.setFuenteHead(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        emp_table.setGridColor(new java.awt.Color(175, 157, 206));
        emp_table.setRowHeight(25);
        emp_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        emp_table.setSelectionForeground(new java.awt.Color(245, 215, 189));
        emp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_table);

        EmpClearFields.setText("Clear fields");
        EmpClearFields.setToolTipText("");
        EmpClearFields.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        EmpClearFields.setkBorderRadius(30);
        EmpClearFields.setkEndColor(new java.awt.Color(175, 157, 206));
        EmpClearFields.setkForeGround(new java.awt.Color(245, 215, 189));
        EmpClearFields.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        EmpClearFields.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        EmpClearFields.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        EmpClearFields.setkPressedColor(new java.awt.Color(242, 179, 65));
        EmpClearFields.setkStartColor(new java.awt.Color(175, 157, 206));
        EmpClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpClearFieldsActionPerformed(evt);
            }
        });

        EmailLbl1.setBackground(new java.awt.Color(0, 0, 0));
        EmailLbl1.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        EmailLbl1.setForeground(new java.awt.Color(0, 0, 0));
        EmailLbl1.setText("position");

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerIDLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmployeeID)
                            .addComponent(txtEmpContact, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerPanelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePanelLayout.createSequentialGroup()
                                .addComponent(EmpSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EmpUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmpFName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustnameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmpLName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmpPositionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addComponent(EmpSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmpClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmpDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReceivablesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerPanelLbl)
                .addGap(18, 18, 18)
                .addComponent(CustomerIDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmpSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(EmpClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailLbl)
                            .addComponent(EmailLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EmployeePanelLayout.createSequentialGroup()
                                .addComponent(txtEmpLName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(Line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmpPositionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(CustnameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpFName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ContactLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(ReceivablesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmpSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSaveBtnActionPerformed
        String fname = txtEmpFName.getText();
        String lname = txtEmpLName.getText();
        String cpn = txtEmpContact.getText();
        String sal = txtEmpSalary.getText();
        int savebtn = JOptionPane.showConfirmDialog(null, "Are you sure you want to save this record?", "Save Record", JOptionPane.YES_NO_OPTION);
        if (savebtn == 0) {
            try {
                if (fname.isEmpty() || lname.isEmpty() || txtEmpPositionCB.getSelectedItem() == null || cpn.isEmpty() || sal.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Don't leave fields empty");
                } else {
                    String sql = "INSERT INTO `employee`(`emp_fname`, `emp_lname`,`emp_position`, `emp_contact`, `salary`) VALUES (?,?,?,?,?)";
                    ps = conn.prepareStatement(sql);

                    ps.setString(1, txtEmpFName.getText());
                    ps.setString(2, txtEmpLName.getText());
                    ps.setString(3, String.valueOf(txtEmpPositionCB.getSelectedItem()));
                    ps.setString(4, txtEmpContact.getText()); //validate only number and must start at 09 regex: ^09\d{9}$
                    ps.setString(5, txtEmpSalary.getText()); //validate only number regex: ^\d{1,8}$

                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Data saved successfully");
                    customerTB_load();
                    txtEmployeeID.setText("");
                    txtEmpFName.setText("");
                    txtEmpLName.setText("");
                    txtEmpContact.setText("");
                    txtEmpSalary.setText("");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_EmpSaveBtnActionPerformed

    private void EmpSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSearchBtnActionPerformed

        String search = txtEmployeeID.getText();
        try {
            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM customer WHERE cust_ID ='" + search + "' ");
            if (rs.next()) {
                txtEmpFName.setText(rs.getString("cust_NAME"));
                txtEmpLName.setText(rs.getString("cust_EMAIL"));
                txtEmpContact.setText(rs.getString("cust_CPNUM"));
                txtEmpSalary.setText(rs.getString("cust_RCV"));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_EmpSearchBtnActionPerformed

    private void EmpUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpUpdateBtnActionPerformed
        String id = txtEmployeeID.getText();
        String fname = txtEmpFName.getText();
        String lname = txtEmpLName.getText();
        String cpn = txtEmpContact.getText();
        String sal = txtEmpSalary.getText();
        try {
            if (id.isEmpty() || fname.isEmpty() || lname.isEmpty() || txtEmpPositionCB.getSelectedItem() == null || cpn.isEmpty() || sal.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Don't leave fields empty");
            } else {
                Statement s = SQLConnection.getConnection().createStatement();
                s.executeUpdate("UPDATE employee SET emp_fname='" + fname + "' ,emp_lname='" + lname + "' ,emp_position='" + txtEmpPositionCB.getSelectedItem() + "' ,emp_contact='" + cpn + "' ,salary='" + sal + "' WHERE emp_id='" + id + "'");

                JOptionPane.showMessageDialog(null, "Data updated successfully");
                customerTB_load();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_EmpUpdateBtnActionPerformed

    private void EmpDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpDelBtnActionPerformed
        String id = txtEmployeeID.getText();
        try {
            Statement s = SQLConnection.getConnection().createStatement();
            s.executeUpdate("DELETE FROM employee WHERE emp_id ='" + id + "'");

            JOptionPane.showMessageDialog(null, "Data deleted successfully");
            customerTB_load();
            txtEmployeeID.setText("");
            txtEmpFName.setText("");
            txtEmpLName.setText("");
            txtEmpContact.setText("");
            txtEmpSalary.setText("");
            txtEmpPositionCB.setSelectedItem(null);

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_EmpDelBtnActionPerformed

    private void emp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tableMouseClicked
        //mouse click & data to textfield
        int r = emp_table.getSelectedRow();

        String id = emp_table.getValueAt(r, 0).toString();
        String fname = emp_table.getValueAt(r, 1).toString();
        String lname = emp_table.getValueAt(r, 2).toString();
        String pos = emp_table.getValueAt(r, 3).toString();
        String contact = emp_table.getValueAt(r, 4).toString();
        String sal = emp_table.getValueAt(r, 5).toString();

        txtEmployeeID.setText(id);
        txtEmpFName.setText(fname);
        txtEmpLName.setText(lname);
        txtEmpPositionCB.setSelectedItem(pos);
        txtEmpContact.setText(contact);
        txtEmpSalary.setText(sal);
    }//GEN-LAST:event_emp_tableMouseClicked

    private void EmpClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpClearFieldsActionPerformed
        txtEmployeeID.setText("");
        txtEmpFName.setText("");
        txtEmpLName.setText("");
        txtEmpContact.setText("");
        txtEmpSalary.setText("");
        txtEmpPositionCB.setSelectedItem(null);
    }//GEN-LAST:event_EmpClearFieldsActionPerformed

    private void txtEmployeeIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIDKeyTyped
        char c = evt.getKeyChar();
        if (txtEmployeeID.getText().length() >= 8) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmployeeIDKeyTyped

    private void txtEmpFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpFNameKeyTyped
        char c = evt.getKeyChar();
        if (txtEmpFName.getText().length() >= 45) {
            evt.consume();
        } else if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpFNameKeyTyped

    private void txtEmpLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpLNameKeyTyped
        char c = evt.getKeyChar();
        if (txtEmpLName.getText().length() >= 45) {
            evt.consume();
        } else if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpLNameKeyTyped

    private void txtEmpContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpContactKeyTyped
        char c = evt.getKeyChar();
        if (txtEmpContact.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpContactKeyTyped

    private void txtEmpSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpSalaryKeyTyped
        char c = evt.getKeyChar();
        if (txtEmpSalary.getText().length() >= 8) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpSalaryKeyTyped

    private void txtEmpFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpFNameKeyReleased
        int position = txtEmpFName.getCaretPosition();
        txtEmpFName.setText(txtEmpFName.getText().toUpperCase());
        txtEmpFName.setCaretPosition(position);
    }//GEN-LAST:event_txtEmpFNameKeyReleased

    private void txtEmpLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpLNameKeyReleased
        int position = txtEmpLName.getCaretPosition();
        txtEmpLName.setText(txtEmpLName.getText().toUpperCase());
        txtEmpLName.setCaretPosition(position);
    }//GEN-LAST:event_txtEmpLNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactLbl;
    private javax.swing.JLabel CustnameLbl;
    private javax.swing.JLabel CustomerIDLbl;
    private javax.swing.JLabel CustomerPanelLbl;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel EmailLbl1;
    private com.k33ptoo.components.KButton EmpClearFields;
    private com.k33ptoo.components.KButton EmpDelBtn;
    private com.k33ptoo.components.KButton EmpSaveBtn;
    private com.k33ptoo.components.KButton EmpSearchBtn;
    private com.k33ptoo.components.KButton EmpUpdateBtn;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JPanel Line1;
    private javax.swing.JPanel Line2;
    private javax.swing.JPanel Line3;
    private javax.swing.JPanel Line4;
    private javax.swing.JPanel Line5;
    private javax.swing.JLabel ReceivablesLbl;
    private rojeru_san.complementos.TableMetro emp_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmpContact;
    private javax.swing.JTextField txtEmpFName;
    private javax.swing.JTextField txtEmpLName;
    private javax.swing.JComboBox<String> txtEmpPositionCB;
    private javax.swing.JTextField txtEmpSalary;
    private javax.swing.JTextField txtEmployeeID;
    // End of variables declaration//GEN-END:variables
}
