/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv_amain;

import java.awt.Image;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR HELIOS 300
 */
public class B_InvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form B_DashboardPanel
     */
    public B_InvoicePanel() {
        initComponents();

        InvoiceLoad();
    }

    public void InvoiceLoad() {
        try {
            DefaultTableModel dt = (DefaultTableModel) sales_table.getModel();
            dt.setRowCount(0);

            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM sales");

            while (rs.next()) {
                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));

                dt.addRow(v);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        //load customer start
        try {

            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM customer");
            Vector v = new Vector();

            while (rs.next()) {
                v.add(rs.getString("cust_NAME"));
                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                CustomersCB.setModel(com);
                //CustomersCB.setSelectedItem(null);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        //load customer end
    }

    public void search_param() {
        String inv_id = txtINIDSearch.getText();
        String stat = StatusCB.getSelectedItem().toString();
        String cnames = CustomersCB.getSelectedItem().toString();

        try {
            DefaultTableModel dt = (DefaultTableModel) sales_table.getModel();
            dt.setRowCount(0);

            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM sales WHERE INID  LIKE '%" + inv_id + "%' AND Cust_NAME LIKE '%" + cnames + "%' AND sales_status LIKE '%" + stat + "%'  ");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));

                dt.addRow(v);

            }

        } catch (Exception e) {

        }
    }

    public void search_name() {
        //  String inv_id = txtINIDSearch.getText();
        // String stat = StatusCB.getSelectedItem().toString();
        String cnames = CustomersCB.getSelectedItem().toString();

        try {
            DefaultTableModel dt = (DefaultTableModel) sales_table.getModel();
            dt.setRowCount(0);

            Statement s = SQLConnection.getConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM sales WHERE Cust_NAME LIKE '%" + cnames + "%'");

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));

                dt.addRow(v);

            }

        } catch (Exception e) {

        }
    }

    public void RemoveAll() {

        txtINIDSearch.setText(""); // clear your All jtextfield text
        CustomersCB.setSelectedIndex(0); // clear your All jtextfield text
        StatusCB.setSelectedIndex(0); // clear your All jtextfield text

        InvoiceLoad(); //  reload your table method 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoicePanel = new javax.swing.JPanel();
        InvoicePanelLbl = new javax.swing.JLabel();
        INIDLbl = new javax.swing.JLabel();
        txtINIDSearch = new javax.swing.JTextField();
        Line4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sales_table = new rojeru_san.complementos.TableMetro();
        CustNameLbl = new javax.swing.JLabel();
        StatusLbl = new javax.swing.JLabel();
        StatusCB = new javax.swing.JComboBox<>();
        RefreshBtn = new com.k33ptoo.components.KButton();
        CustomersCB = new javax.swing.JComboBox<>();
        DelRec = new com.k33ptoo.components.KButton();

        InvoicePanel.setBackground(new java.awt.Color(245, 215, 189));
        InvoicePanel.setForeground(new java.awt.Color(245, 215, 189));
        InvoicePanel.setMaximumSize(new java.awt.Dimension(890, 650));
        InvoicePanel.setPreferredSize(new java.awt.Dimension(890, 650));

        InvoicePanelLbl.setBackground(new java.awt.Color(0, 0, 0));
        InvoicePanelLbl.setFont(new java.awt.Font("Retro Computer", 1, 18)); // NOI18N
        InvoicePanelLbl.setForeground(new java.awt.Color(0, 0, 0));
        InvoicePanelLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoicePanelLbl.setText("invoice panel ");
        InvoicePanelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InvoicePanelLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        InvoicePanelLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        InvoicePanelLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        INIDLbl.setBackground(new java.awt.Color(0, 0, 0));
        INIDLbl.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        INIDLbl.setForeground(new java.awt.Color(0, 0, 0));
        INIDLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        INIDLbl.setText("INID:");
        INIDLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INIDLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        INIDLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        INIDLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        txtINIDSearch.setBackground(new java.awt.Color(245, 215, 189));
        txtINIDSearch.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        txtINIDSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtINIDSearch.setBorder(null);
        txtINIDSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtINIDSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtINIDSearchKeyTyped(evt);
            }
        });

        Line4.setBackground(new java.awt.Color(175, 157, 206));
        Line4.setPreferredSize(new java.awt.Dimension(138, 3));

        javax.swing.GroupLayout Line4Layout = new javax.swing.GroupLayout(Line4);
        Line4.setLayout(Line4Layout);
        Line4Layout.setHorizontalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        Line4Layout.setVerticalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(245, 215, 189));
        jScrollPane1.setForeground(new java.awt.Color(245, 215, 189));

        sales_table.setBackground(new java.awt.Color(245, 215, 189));
        sales_table.setForeground(new java.awt.Color(245, 215, 189));
        sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SALESID", "INID", "CUSTID", "CUSTNAME", "TOTAL QTY", "TOTAL AMT", "STATUS", "CHANGE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sales_table.setColorBackgoundHead(new java.awt.Color(142, 126, 167));
        sales_table.setColorBordeFilas(new java.awt.Color(175, 157, 206));
        sales_table.setColorBordeHead(new java.awt.Color(175, 157, 206));
        sales_table.setColorFilasBackgound1(new java.awt.Color(245, 215, 189));
        sales_table.setColorFilasBackgound2(new java.awt.Color(245, 215, 189));
        sales_table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        sales_table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        sales_table.setColorForegroundHead(new java.awt.Color(245, 215, 189));
        sales_table.setColorSelBackgound(new java.awt.Color(255, 255, 255));
        sales_table.setColorSelForeground(new java.awt.Color(0, 0, 0));
        sales_table.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        sales_table.setFuenteFilas(new java.awt.Font("Arial", 0, 10)); // NOI18N
        sales_table.setFuenteFilasSelect(new java.awt.Font("Arial", 0, 10)); // NOI18N
        sales_table.setFuenteHead(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        sales_table.setGridColor(new java.awt.Color(175, 157, 206));
        sales_table.setRowHeight(25);
        sales_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        sales_table.setSelectionForeground(new java.awt.Color(245, 215, 189));
        jScrollPane1.setViewportView(sales_table);

        CustNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        CustNameLbl.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        CustNameLbl.setForeground(new java.awt.Color(0, 0, 0));
        CustNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustNameLbl.setText("customer name:");
        CustNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustNameLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        CustNameLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        CustNameLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        StatusLbl.setBackground(new java.awt.Color(0, 0, 0));
        StatusLbl.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        StatusLbl.setForeground(new java.awt.Color(0, 0, 0));
        StatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StatusLbl.setText("status:");
        StatusLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatusLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        StatusLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        StatusLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        StatusCB.setBackground(new java.awt.Color(255, 255, 255));
        StatusCB.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        StatusCB.setForeground(new java.awt.Color(0, 0, 0));
        StatusCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Unsettled", "Partial", "Paid" }));
        StatusCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatusCB.setMaximumSize(new java.awt.Dimension(229, 20));
        StatusCB.setMinimumSize(new java.awt.Dimension(229, 20));
        StatusCB.setPreferredSize(new java.awt.Dimension(229, 20));
        StatusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusCBActionPerformed(evt);
            }
        });

        RefreshBtn.setText("refresh");
        RefreshBtn.setAlignmentY(0.0F);
        RefreshBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        RefreshBtn.setkBorderRadius(30);
        RefreshBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        RefreshBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        RefreshBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        RefreshBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        RefreshBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        RefreshBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        RefreshBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        CustomersCB.setBackground(new java.awt.Color(255, 255, 255));
        CustomersCB.setFont(new java.awt.Font("Retro Computer", 0, 12)); // NOI18N
        CustomersCB.setForeground(new java.awt.Color(0, 0, 0));
        CustomersCB.setSelectedItem(null);
        CustomersCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomersCB.setMaximumSize(new java.awt.Dimension(229, 20));
        CustomersCB.setMinimumSize(new java.awt.Dimension(229, 20));
        CustomersCB.setPreferredSize(new java.awt.Dimension(229, 20));
        CustomersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersCBActionPerformed(evt);
            }
        });

        DelRec.setText("DELETE ALL RECORDS");
        DelRec.setAlignmentY(0.0F);
        DelRec.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        DelRec.setkBorderRadius(30);
        DelRec.setkEndColor(new java.awt.Color(175, 157, 206));
        DelRec.setkForeGround(new java.awt.Color(245, 215, 189));
        DelRec.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        DelRec.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        DelRec.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        DelRec.setkPressedColor(new java.awt.Color(242, 179, 65));
        DelRec.setkStartColor(new java.awt.Color(175, 157, 206));
        DelRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InvoicePanelLayout.createSequentialGroup()
                                .addComponent(StatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StatusCB, 0, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InvoicePanelLayout.createSequentialGroup()
                                .addComponent(INIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtINIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomersCB, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InvoicePanelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelRec, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(INIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtINIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CustNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomersCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(InvoicePanelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DelRec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InvoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InvoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtINIDSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINIDSearchKeyReleased
        search_param();
    }//GEN-LAST:event_txtINIDSearchKeyReleased

    private void StatusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCBActionPerformed
        search_param();

        if (StatusCB.getSelectedItem().toString().equals("All")) {
            RemoveAll();
        }
    }//GEN-LAST:event_StatusCBActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        RemoveAll();
        InvoiceLoad();
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void CustomersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersCBActionPerformed
        search_name();
    }//GEN-LAST:event_CustomersCBActionPerformed

    private void txtINIDSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINIDSearchKeyTyped
        char c = evt.getKeyChar();
        if (txtINIDSearch.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtINIDSearchKeyTyped

    private void DelRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelRecActionPerformed
        int delbtn = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all records?\nTip: Print the All Invoice Reports first before deleteing.",
                "Delete Records", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if (delbtn == 0) {
            try {
                Statement s = SQLConnection.getConnection().createStatement();
                s.executeUpdate("DELETE FROM `sales`");//delete all rows from this table

                JOptionPane.showMessageDialog(null, "Records deleted successfully");
                InvoiceLoad();
                txtINIDSearch.setText("");
                CustomersCB.setSelectedItem(null);
                StatusCB.setSelectedItem(null);

            } catch (Exception ex) {
              //  JOptionPane.showMessageDialog(null, ex);
                System.out.println(ex);
            }

        }
    }//GEN-LAST:event_DelRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustNameLbl;
    private javax.swing.JComboBox<String> CustomersCB;
    private com.k33ptoo.components.KButton DelRec;
    private javax.swing.JLabel INIDLbl;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JLabel InvoicePanelLbl;
    private javax.swing.JPanel Line4;
    private com.k33ptoo.components.KButton RefreshBtn;
    private javax.swing.JComboBox<String> StatusCB;
    private javax.swing.JLabel StatusLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.TableMetro sales_table;
    private javax.swing.JTextField txtINIDSearch;
    // End of variables declaration//GEN-END:variables
}
