/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv_amain;

import java.awt.Image;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR HELIOS 300
 */
public class B_ReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form B_DashboardPanel
     */
    public B_ReportsPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoicePanel = new javax.swing.JPanel();
        InvoicePanelLbl = new javax.swing.JLabel();
        invreport = new javax.swing.JLabel();
        VAInvBtn = new com.k33ptoo.components.KButton();
        INIDLbl = new javax.swing.JLabel();
        para_inid = new javax.swing.JTextField();
        Line4 = new javax.swing.JPanel();
        ViewInvBtn = new com.k33ptoo.components.KButton();
        custReport = new javax.swing.JLabel();
        VACustBtn = new com.k33ptoo.components.KButton();
        INIDLbl1 = new javax.swing.JLabel();
        para_cust = new javax.swing.JTextField();
        Line5 = new javax.swing.JPanel();
        ViewCustBtn = new com.k33ptoo.components.KButton();
        empReport = new javax.swing.JLabel();
        VAEmpBtn = new com.k33ptoo.components.KButton();
        INIDLbl2 = new javax.swing.JLabel();
        para_emp = new javax.swing.JTextField();
        Line6 = new javax.swing.JPanel();
        ViewEmpBtn = new com.k33ptoo.components.KButton();
        InveReport = new javax.swing.JLabel();
        VAInveBtn = new com.k33ptoo.components.KButton();
        INIDLbl3 = new javax.swing.JLabel();
        para_Inve = new javax.swing.JTextField();
        Line7 = new javax.swing.JPanel();
        ViewInveBtn = new com.k33ptoo.components.KButton();
        InveReport1 = new javax.swing.JLabel();
        VAInveBtn1 = new com.k33ptoo.components.KButton();

        InvoicePanel.setBackground(new java.awt.Color(245, 215, 189));
        InvoicePanel.setForeground(new java.awt.Color(245, 215, 189));
        InvoicePanel.setMaximumSize(new java.awt.Dimension(890, 650));
        InvoicePanel.setPreferredSize(new java.awt.Dimension(890, 650));

        InvoicePanelLbl.setBackground(new java.awt.Color(0, 0, 0));
        InvoicePanelLbl.setFont(new java.awt.Font("Retro Computer", 1, 18)); // NOI18N
        InvoicePanelLbl.setForeground(new java.awt.Color(0, 0, 0));
        InvoicePanelLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InvoicePanelLbl.setText("REPORTS panel ");
        InvoicePanelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InvoicePanelLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        InvoicePanelLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        InvoicePanelLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        invreport.setBackground(new java.awt.Color(0, 0, 0));
        invreport.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        invreport.setForeground(new java.awt.Color(0, 0, 0));
        invreport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invreport.setText("invoice report");
        invreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invreport.setMaximumSize(new java.awt.Dimension(220, 24));
        invreport.setMinimumSize(new java.awt.Dimension(220, 24));
        invreport.setPreferredSize(new java.awt.Dimension(220, 24));

        VAInvBtn.setText("VIEW ALL invoice REPORTS");
        VAInvBtn.setAlignmentY(0.0F);
        VAInvBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        VAInvBtn.setkBorderRadius(30);
        VAInvBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        VAInvBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        VAInvBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        VAInvBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        VAInvBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        VAInvBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        VAInvBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        VAInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAInvBtnActionPerformed(evt);
            }
        });

        INIDLbl.setBackground(new java.awt.Color(0, 0, 0));
        INIDLbl.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        INIDLbl.setForeground(new java.awt.Color(0, 0, 0));
        INIDLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        INIDLbl.setText("INVOICE ID:");
        INIDLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INIDLbl.setMaximumSize(new java.awt.Dimension(220, 24));
        INIDLbl.setMinimumSize(new java.awt.Dimension(220, 24));
        INIDLbl.setPreferredSize(new java.awt.Dimension(220, 24));

        para_inid.setBackground(new java.awt.Color(245, 215, 189));
        para_inid.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        para_inid.setForeground(new java.awt.Color(0, 0, 0));
        para_inid.setBorder(null);
        para_inid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                para_inidKeyTyped(evt);
            }
        });

        Line4.setBackground(new java.awt.Color(175, 157, 206));
        Line4.setPreferredSize(new java.awt.Dimension(138, 3));

        javax.swing.GroupLayout Line4Layout = new javax.swing.GroupLayout(Line4);
        Line4.setLayout(Line4Layout);
        Line4Layout.setHorizontalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Line4Layout.setVerticalGroup(
            Line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ViewInvBtn.setText("VIEW invoice");
        ViewInvBtn.setAlignmentY(0.0F);
        ViewInvBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        ViewInvBtn.setkBorderRadius(30);
        ViewInvBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        ViewInvBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        ViewInvBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        ViewInvBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        ViewInvBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        ViewInvBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        ViewInvBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        ViewInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInvBtnActionPerformed(evt);
            }
        });

        custReport.setBackground(new java.awt.Color(0, 0, 0));
        custReport.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        custReport.setForeground(new java.awt.Color(0, 0, 0));
        custReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        custReport.setText("customer data");
        custReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custReport.setMaximumSize(new java.awt.Dimension(220, 24));
        custReport.setMinimumSize(new java.awt.Dimension(220, 24));
        custReport.setPreferredSize(new java.awt.Dimension(220, 24));

        VACustBtn.setText("VIEW ALL customer REPORTS");
        VACustBtn.setAlignmentY(0.0F);
        VACustBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        VACustBtn.setkBorderRadius(30);
        VACustBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        VACustBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        VACustBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        VACustBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        VACustBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        VACustBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        VACustBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        VACustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VACustBtnActionPerformed(evt);
            }
        });

        INIDLbl1.setBackground(new java.awt.Color(0, 0, 0));
        INIDLbl1.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        INIDLbl1.setForeground(new java.awt.Color(0, 0, 0));
        INIDLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        INIDLbl1.setText("customer ID:");
        INIDLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INIDLbl1.setMaximumSize(new java.awt.Dimension(220, 24));
        INIDLbl1.setMinimumSize(new java.awt.Dimension(220, 24));
        INIDLbl1.setPreferredSize(new java.awt.Dimension(220, 24));

        para_cust.setBackground(new java.awt.Color(245, 215, 189));
        para_cust.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        para_cust.setForeground(new java.awt.Color(0, 0, 0));
        para_cust.setBorder(null);
        para_cust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                para_custKeyTyped(evt);
            }
        });

        Line5.setBackground(new java.awt.Color(175, 157, 206));
        Line5.setPreferredSize(new java.awt.Dimension(138, 3));

        javax.swing.GroupLayout Line5Layout = new javax.swing.GroupLayout(Line5);
        Line5.setLayout(Line5Layout);
        Line5Layout.setHorizontalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        Line5Layout.setVerticalGroup(
            Line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ViewCustBtn.setText("VIEW customer");
        ViewCustBtn.setAlignmentY(0.0F);
        ViewCustBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        ViewCustBtn.setkBorderRadius(30);
        ViewCustBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        ViewCustBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        ViewCustBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        ViewCustBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        ViewCustBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        ViewCustBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        ViewCustBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        ViewCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustBtnActionPerformed(evt);
            }
        });

        empReport.setBackground(new java.awt.Color(0, 0, 0));
        empReport.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        empReport.setForeground(new java.awt.Color(0, 0, 0));
        empReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empReport.setText("employee data");
        empReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empReport.setMaximumSize(new java.awt.Dimension(220, 24));
        empReport.setMinimumSize(new java.awt.Dimension(220, 24));
        empReport.setPreferredSize(new java.awt.Dimension(220, 24));

        VAEmpBtn.setText("VIEW ALL employee REPORTS");
        VAEmpBtn.setAlignmentY(0.0F);
        VAEmpBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        VAEmpBtn.setkBorderRadius(30);
        VAEmpBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        VAEmpBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        VAEmpBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        VAEmpBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        VAEmpBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        VAEmpBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        VAEmpBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        VAEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAEmpBtnActionPerformed(evt);
            }
        });

        INIDLbl2.setBackground(new java.awt.Color(0, 0, 0));
        INIDLbl2.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        INIDLbl2.setForeground(new java.awt.Color(0, 0, 0));
        INIDLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        INIDLbl2.setText("employee id:");
        INIDLbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INIDLbl2.setMaximumSize(new java.awt.Dimension(220, 24));
        INIDLbl2.setMinimumSize(new java.awt.Dimension(220, 24));
        INIDLbl2.setPreferredSize(new java.awt.Dimension(220, 24));

        para_emp.setBackground(new java.awt.Color(245, 215, 189));
        para_emp.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        para_emp.setForeground(new java.awt.Color(0, 0, 0));
        para_emp.setBorder(null);
        para_emp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                para_empKeyTyped(evt);
            }
        });

        Line6.setBackground(new java.awt.Color(175, 157, 206));
        Line6.setPreferredSize(new java.awt.Dimension(138, 3));

        javax.swing.GroupLayout Line6Layout = new javax.swing.GroupLayout(Line6);
        Line6.setLayout(Line6Layout);
        Line6Layout.setHorizontalGroup(
            Line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        Line6Layout.setVerticalGroup(
            Line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ViewEmpBtn.setText("VIEW employee");
        ViewEmpBtn.setAlignmentY(0.0F);
        ViewEmpBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        ViewEmpBtn.setkBorderRadius(30);
        ViewEmpBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        ViewEmpBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        ViewEmpBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        ViewEmpBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        ViewEmpBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        ViewEmpBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        ViewEmpBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        ViewEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmpBtnActionPerformed(evt);
            }
        });

        InveReport.setBackground(new java.awt.Color(0, 0, 0));
        InveReport.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        InveReport.setForeground(new java.awt.Color(0, 0, 0));
        InveReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InveReport.setText("inventory report");
        InveReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InveReport.setMaximumSize(new java.awt.Dimension(220, 24));
        InveReport.setMinimumSize(new java.awt.Dimension(220, 24));
        InveReport.setPreferredSize(new java.awt.Dimension(220, 24));

        VAInveBtn.setText("VIEW ALL inventory REPORTS");
        VAInveBtn.setAlignmentY(0.0F);
        VAInveBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        VAInveBtn.setkBorderRadius(30);
        VAInveBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        VAInveBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        VAInveBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        VAInveBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        VAInveBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        VAInveBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        VAInveBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        VAInveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAInveBtnActionPerformed(evt);
            }
        });

        INIDLbl3.setBackground(new java.awt.Color(0, 0, 0));
        INIDLbl3.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        INIDLbl3.setForeground(new java.awt.Color(0, 0, 0));
        INIDLbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        INIDLbl3.setText("upc:");
        INIDLbl3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INIDLbl3.setMaximumSize(new java.awt.Dimension(220, 24));
        INIDLbl3.setMinimumSize(new java.awt.Dimension(220, 24));
        INIDLbl3.setPreferredSize(new java.awt.Dimension(220, 24));

        para_Inve.setBackground(new java.awt.Color(245, 215, 189));
        para_Inve.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        para_Inve.setForeground(new java.awt.Color(0, 0, 0));
        para_Inve.setBorder(null);
        para_Inve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                para_InveKeyTyped(evt);
            }
        });

        Line7.setBackground(new java.awt.Color(175, 157, 206));
        Line7.setPreferredSize(new java.awt.Dimension(138, 3));

        javax.swing.GroupLayout Line7Layout = new javax.swing.GroupLayout(Line7);
        Line7.setLayout(Line7Layout);
        Line7Layout.setHorizontalGroup(
            Line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        Line7Layout.setVerticalGroup(
            Line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ViewInveBtn.setText("VIEW inventory");
        ViewInveBtn.setAlignmentY(0.0F);
        ViewInveBtn.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        ViewInveBtn.setkBorderRadius(30);
        ViewInveBtn.setkEndColor(new java.awt.Color(175, 157, 206));
        ViewInveBtn.setkForeGround(new java.awt.Color(245, 215, 189));
        ViewInveBtn.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        ViewInveBtn.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        ViewInveBtn.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        ViewInveBtn.setkPressedColor(new java.awt.Color(242, 179, 65));
        ViewInveBtn.setkStartColor(new java.awt.Color(175, 157, 206));
        ViewInveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInveBtnActionPerformed(evt);
            }
        });

        InveReport1.setBackground(new java.awt.Color(0, 0, 0));
        InveReport1.setFont(new java.awt.Font("Retro Computer", 1, 14)); // NOI18N
        InveReport1.setForeground(new java.awt.Color(0, 0, 0));
        InveReport1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InveReport1.setText("CART report");
        InveReport1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InveReport1.setMaximumSize(new java.awt.Dimension(220, 24));
        InveReport1.setMinimumSize(new java.awt.Dimension(220, 24));
        InveReport1.setPreferredSize(new java.awt.Dimension(220, 24));

        VAInveBtn1.setText("VIEW ALL CART REPORTS");
        VAInveBtn1.setAlignmentY(0.0F);
        VAInveBtn1.setFont(new java.awt.Font("Retro Computer", 1, 12)); // NOI18N
        VAInveBtn1.setkBorderRadius(30);
        VAInveBtn1.setkEndColor(new java.awt.Color(175, 157, 206));
        VAInveBtn1.setkForeGround(new java.awt.Color(245, 215, 189));
        VAInveBtn1.setkHoverEndColor(new java.awt.Color(245, 195, 152));
        VAInveBtn1.setkHoverForeGround(new java.awt.Color(175, 157, 206));
        VAInveBtn1.setkHoverStartColor(new java.awt.Color(245, 195, 152));
        VAInveBtn1.setkPressedColor(new java.awt.Color(242, 179, 65));
        VAInveBtn1.setkStartColor(new java.awt.Color(175, 157, 206));
        VAInveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAInveBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INIDLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INIDLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INIDLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InvoicePanelLayout.createSequentialGroup()
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(para_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(para_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Line6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(para_Inve, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Line7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ViewCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewInveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(InvoicePanelLayout.createSequentialGroup()
                                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Line4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(para_inid, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ViewInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(VAInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(invreport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InvoicePanelLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InveReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InveReport1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(VACustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VAEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VAInveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VAInveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(InvoicePanelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invreport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VAInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(para_inid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewInvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(custReport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VACustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INIDLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(para_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(empReport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VAEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INIDLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(para_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(InveReport, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VAInveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INIDLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(para_Inve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Line7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewInveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(InveReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VAInveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InvoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InvoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VAInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAInvBtnActionPerformed
        try {
            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\inidreport.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_VAInvBtnActionPerformed

    private void ViewInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInvBtnActionPerformed
        String txtf = para_inid.getText().toString();
        if (txtf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Text Field is empty!");
        } else {
            HashMap para = new HashMap();

            para.put("invo_para"/*from Jaspersoft ireport*/, para_inid.getText());

            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\reportsearch.jasper", para);
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center
            para_inid.setText("");
        }
    }//GEN-LAST:event_ViewInvBtnActionPerformed

    private void VACustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VACustBtnActionPerformed
        try {
            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\AllCustomer.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_VACustBtnActionPerformed

    private void ViewCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustBtnActionPerformed
        String txtf = para_cust.getText().toString();
        if (txtf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Text Field is empty!");
        } else {
            HashMap para = new HashMap();

            para.put("Para_cusID"/*from Jaspersoft ireport*/, para_cust.getText());

            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\SearchCustomer.jasper", para);
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center
            para_cust.setText("");
        }
    }//GEN-LAST:event_ViewCustBtnActionPerformed

    private void VAEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAEmpBtnActionPerformed
        try {
            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\AllEmployee.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_VAEmpBtnActionPerformed

    private void ViewEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmpBtnActionPerformed
        String txtf = para_emp.getText().toString();
        if (txtf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Text Field is empty!");
        } else {
            HashMap para = new HashMap();

            para.put("Para_empID"/*from Jaspersoft ireport*/, para_emp.getText());

            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\SearchEmployee.jasper", para);
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center
            para_emp.setText("");
        }
    }//GEN-LAST:event_ViewEmpBtnActionPerformed

    private void VAInveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAInveBtnActionPerformed
        try {
            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\AllInventory_test.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_VAInveBtnActionPerformed

    private void ViewInveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInveBtnActionPerformed
        String txtf = para_Inve.getText().toString();
        if (txtf.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Text Field is empty!");
        } else {
            HashMap para = new HashMap();

            para.put("Para_upc"/*from Jaspersoft ireport*/, para_Inve.getText());

            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\SearchInventory_test.jasper", para);
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center
            para_Inve.setText("");
        }
    }//GEN-LAST:event_ViewInveBtnActionPerformed

    private void para_inidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_inidKeyTyped
        char c = evt.getKeyChar();
        if (para_inid.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_para_inidKeyTyped

    private void para_custKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_custKeyTyped
        char c = evt.getKeyChar();
        if (para_cust.getText().length() >= 30) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_para_custKeyTyped

    private void para_empKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_empKeyTyped
        char c = evt.getKeyChar();
        if (para_emp.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_para_empKeyTyped

    private void para_InveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_para_InveKeyTyped
        char c = evt.getKeyChar();
        if (para_Inve.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_para_InveKeyTyped

    private void VAInveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAInveBtn1ActionPerformed
        try {
            Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\cartreport.jasper");
            r.setVisible(true);
            r.setLocationRelativeTo(null);//Center

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_VAInveBtn1ActionPerformed
    
    /*
    String txtf = para_CartRep.getText().toString();
        if(txtf.isEmpty()){
            JOptionPane.showMessageDialog(null, "Text Field is empty!");
        } else{
            HashMap para = new HashMap();
        
        para.put("para_inid", para_CartRep.getText());
        
        Inv_ReportView r = new Inv_ReportView("src\\inv_reports\\SearchCartreport.jasper",para);
        r.setVisible(true);
        r.setLocationRelativeTo(null);//Center
        para_CartRep.setText("");
        }
    
        char c = evt.getKeyChar();
        if (para_inid.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(c)) {
            evt.consume();
        } else if (Character.isAlphabetic(c)) {
            evt.consume();
        } else if (Character.isLetter(c)) {
            evt.consume();
        } else if (Character.isSpaceChar(c)) {
            evt.consume();
        }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel INIDLbl;
    private javax.swing.JLabel INIDLbl1;
    private javax.swing.JLabel INIDLbl2;
    private javax.swing.JLabel INIDLbl3;
    private javax.swing.JLabel InveReport;
    private javax.swing.JLabel InveReport1;
    private javax.swing.JPanel InvoicePanel;
    private javax.swing.JLabel InvoicePanelLbl;
    private javax.swing.JPanel Line4;
    private javax.swing.JPanel Line5;
    private javax.swing.JPanel Line6;
    private javax.swing.JPanel Line7;
    private com.k33ptoo.components.KButton VACustBtn;
    private com.k33ptoo.components.KButton VAEmpBtn;
    private com.k33ptoo.components.KButton VAInvBtn;
    private com.k33ptoo.components.KButton VAInveBtn;
    private com.k33ptoo.components.KButton VAInveBtn1;
    private com.k33ptoo.components.KButton ViewCustBtn;
    private com.k33ptoo.components.KButton ViewEmpBtn;
    private com.k33ptoo.components.KButton ViewInvBtn;
    private com.k33ptoo.components.KButton ViewInveBtn;
    private javax.swing.JLabel custReport;
    private javax.swing.JLabel empReport;
    private javax.swing.JLabel invreport;
    private javax.swing.JTextField para_Inve;
    private javax.swing.JTextField para_cust;
    private javax.swing.JTextField para_emp;
    private javax.swing.JTextField para_inid;
    // End of variables declaration//GEN-END:variables
}
